#ifndef ROS_TALKER_GLOBAL_H
#define ROS_TALKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROS_TALKER_LIBRARY)
#  define ROS_TALKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ROS_TALKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ROS_TALKER_GLOBAL_H
